export default (
  '<div class="viewer-container-custom"><div class="viewer-container" touch-action="none">'
  + '<div class="viewer-previewBox"><div class="viewer-preview"></div></div>'
    + '<div class="viewer-canvas"></div>'
    + '<div class="viewer-artwork"><a target="_black">查看原图</a></div>'
    + '<div class="viewer-footer">'
      + '<div class="viewer-title"></div>'
      + '<div class="viewer-toolbar"></div>'
      + '<div class="viewer-tip">提示：使用方向键 ↑ ↓ 键切换上一笔、下一笔费用，使用方向键 ← → 在多张图片中进行切换。</div>'
      + '<div class="viewer-navbar">'
        + '<ul class="viewer-list"></ul>'
      + '</div>' 
    + '</div>'
    + '<div class="viewer-tooltip"></div>'
    + '<div role="button" class="viewer-button" data-viewer-action="mix"></div>'
    + '<div class="viewer-player"></div>'
  + '</div></div>'
);
